- name: Load environment yml
  block:
    - copy:
        src: ../files/environment.yml
        dest: ~/environment.yml
    - shell: 'cat ~/environment.yml'
      register: environment_yml
    - set_fact: 
        env_name: "{{ environment_yml.stdout | regex_search('name\\: (.*)','\\1') | first }}"


# Necessary for idempotence
- name: Check if conda virtual environment exist
  shell: '. ~/.profile && conda env list'
  register: env_exist

- name: Create conda virtual environment
  block:
    - copy:
        src: ../files/environment.yml
        dest: ~/environment.yml
    - shell: '. ~/.profile && conda env create -f environment.yml'
  when: '"{{ env_name }}" not in env_exist.stdout'
